name: Build and publish Python package

on:
  workflow_run:
    workflows: ["Python Tests"]
    types:
      - completed

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'

    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.workflow_run.head_sha }}

    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry build

    - name: Build package
      run: poetry build

    - name: Rebuild package with version tag
      if: startsWith(github.event.workflow_run.head_branch, 'v')
      run: |
        VERSION=${github.event.workflow_run.head_branch#v}
        poetry version $VERSION
        poetry build

    - name: Publish to PyPI
      if: startsWith(github.event.workflow_run.head_branch, 'v')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: dist/
        skip-existing: true
        verify-metadata: true
